name: CI-CD

on:
    push:
      branches: [ "master" ]

jobs:
  check-dist:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
      
    - name: Install dependecies
      run: npm ci
    
    - name: Build    
      run: npm run build --if-present
    
    - name: Run tests
      run: npm run test
      
    - name: Lint
      run: npx eslint src/**/*.ts
      
    - name: Run ts-prune  
      run: npm run find-deadcode
      
    
      
   
        
